<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2020/11/05 21:10:57

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'symfony',
  'password' => 'symfony',
  'name' => 'doctrine',
)),);
